### ISSUE TITLE
Лучше оставить только один из двух (а второй высчитывать на базе первого)

### ISSUE THREAD

**Issue by coursar** [AleksandrNagovitsyn/Ozon#3]
https://github.com/AleksandrNagovitsyn/Ozon/blob/137305e1c38c1b3c0bd8b6e1ab3e20f2a52c0874/src/main/java/ru/itpark/Product.java#L9-L10

Т.к. в противном случае можно прийти к неконсистентному состоянию

**Comment by AleksandrNagovitsyn** [comment]
@coursar что значит не консистентное состояние? 
Если это не приведет к ошибке, я бы не стал их объединять: это два самостоятельных значения

**Comment by coursar** [comment]
Цена с дисконтом высчитывается на базе дисконта. Зачем вам два поля для этого?

**Comment by AleksandrNagovitsyn** [comment]
@coursar 
Потому что я вижу только одно решение, как их объединить :
убрать эту строку https://github.com/AleksandrNagovitsyn/Ozon/blob/e6e211ca3c3a798cc4001a73a1ce167209247b0f/src/main/java/ru/itpark/Product.java#L10

и заменить эту https://github.com/AleksandrNagovitsyn/Ozon/blob/e6e211ca3c3a798cc4001a73a1ce167209247b0f/src/main/java/ru/itpark/Product.java#L17

на такой код: 
 discountPerPercent = price - price / 100 * discountPerPercent


Но в таком случае, я переменной, которая должна отображать **скидку в %**, присваиваю значение **итоговой суммы**. 

А если я захочу узнать скидку в %? 
System.out.println(discountPerPercent) мне выведет совсем не то, чего я жду.
Это же не корректно. 

Или есть другой вариант объединить эти поля?

**Comment by coursar** [comment]
У вас есть:
```java
private int price;
private int discount;

public int getPriceWithDiscount() {
    return price - price * discount / 100;
}
```
